# Starship configuration - Version personnalisÃ©e
format = """
$directory\
$git_branch\
$git_status\
$git_metrics\
$package\
$nodejs\
$golang\
$docker_context\
$cmd_duration\
$character"""

[directory]
truncation_length = 0
truncation_symbol = ""
home_symbol = "ğŸ "
read_only = "ğŸ”’"
style = "cyan"
format = "[/$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "ï˜ "
style = "purple"

[git_commit]
tag_symbol = ' ï’ '

[git_status]
disabled = true
format = "[$all_status]($style) "
style = "red"
conflicted = "âš¡"
ahead = "â¬†ï¸${count}"
behind = "â¬‡ï¸${count}"
diverged = "ğŸ”€"
up_to_date = ""
untracked = "â“ ${count}"
stashed = "ğŸ“¦ ${count}"
modified = "âœï¸ ${count}"
staged = "âœ… ${count}"
renamed = "ğŸ“ ${count}"
deleted = "ğŸ—‘ï¸ ${count}"

[git_metrics]
disabled = false
format = "([+$added]($added_style))([-$deleted]($deleted_style) )"

[package]
format = "[$symbol$version]($style) "
display_private = true

[gcloud]
symbol = "îŒ½  "

[golang]
symbol = "î˜§ "

[java]
symbol = "î‰– "

[nodejs]

[docker_context]
format = "[$symbol$context]($style) "
symbol = "ğŸ³ "
style = "cyan"
only_with_files = true

[cmd_duration]
min_time = 2_000
format = "â±ï¸[$duration]($style) "
style = "yellow"

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"
vimcmd_symbol = "[â®](green)"